import { NextRequest, NextResponse } from "next/server";
import { ZodError } from "zod"; // Import ZodError for specific error handling
import bcrypt from "bcrypt";
import clientPromise from "@/lib/database/mongodb";
import { generateOTP } from "@/lib/otp/genarate-otp";
import { sendOTPEmail } from "@/lib/email/send-otp"; // Adjust path if necessary
import { Db } from "mongodb"; // Import ObjectId for _id type if needed for schema
import { User } from "@/models/userSchema"; // IMPORTANT: Import User type from your schema file
import { userSchema } from "@/models/userSchema";

// Define a type for the user document as it will be stored in MongoDB.
// This should ideally align with your Zod schema and database model.
// We are now importing 'User' from '@/models/userSchema', so this local definition is removed.
// interface User { ... } // REMOVED: Replaced by import from userSchema

/**
 * Handles POST requests for user registration (signup).
 * Validates input, checks for existing users, hashes passwords, generates OTPs,
 * sends verification emails, and stores user data in MongoDB.
 */
export async function POST(req: NextRequest) {
  try {
    const body: unknown = await req.json(); // Use 'unknown' for initial parsed body

    // Validate input using Zod.
    // userSchema.omit is used to exclude fields that are not part of the client's input
    // but are generated/managed by the server (e.g., _id, emailVerified, role, etc.)
    const parsed = userSchema.omit({
      _id: true, // MongoDB generates this
      emailVerified: true, // Set by server, not client input
      role: true, // Defaulted by server, not client input
      avatar: true, // Optional, but not required on signup
      isActive: true, // Defaulted by server
      lastLogin: true, // Set by server
      provider: true, // Defaulted by server
      phone: true, // Optional, not required on signup
      otp: true, // Generated by server
      otpExpiry: true, // Generated by server
      createdAt: true, // Set by server
      updatedAt: true, // Set by server
    }).safeParse(body); // Use safeParse for validation and error handling

    // If Zod validation fails, return a 400 Bad Request with the validation error message
    if (!parsed.success) {
      console.warn("[Signup API] Input validation failed:", parsed.error.errors[0].message);
      return NextResponse.json(
        { error: parsed.error.errors[0].message },
        { status: 400 }
      );
    }

    // Normalize email to lowercase for consistency in database storage and lookups
    const email = parsed.data.email.toLowerCase();

    const client = await clientPromise;
    const db: Db = client.db("auth"); // Assuming your database name is "auth"
    // FIX: Explicitly type the collection with the imported User type
    const usersCollection = db.collection<User>("users");

    // Check if email already exists (case-insensitive search)
    const existingUser = await usersCollection.findOne({
      email: { $regex: `^${email}$`, $options: "i" },
    });
    if (existingUser) {
      console.warn(`[Signup API] Registration attempt with existing email: ${email}`);
      return NextResponse.json(
        { error: "Email already registered. Please sign in or use a different email." },
        { status: 409 } // 409 Conflict status code
      );
    }

    // Hash password using bcrypt
    const hashedPassword = await bcrypt.hash(parsed.data.password, 10);

    // Generate OTP and set its expiry date (10 minutes from now)
    const otp = generateOTP();
    const otpExpiry = new Date(Date.now() + 10 * 60 * 1000);

    // Prepare the new user object for insertion into the database
    // FIX: Explicitly type newUser as User
    const newUser: User = {
      name: parsed.data.name,
      email, // Use normalized email
      password: hashedPassword,
      emailVerified: false, // New users are not verified by default
      role: "user", // Default role for new signups
      isActive: true, // User is active upon signup
      provider: "credentials", // Authentication provider
      otp,
      otpExpiry,
      createdAt: new Date(),
      updatedAt: new Date(),
      // Ensure all required fields from userSchema are present or have defaults
      // If userSchema has optional fields like 'avatar', 'phone', 'lastLogin',
      // they can be omitted here or explicitly set to undefined/null if not provided by client.
    };

    // Insert the new user document into the database
    await usersCollection.insertOne(newUser);

    // Send OTP email for verification.
    // Wrap in try/catch to ensure signup process doesn't fail if email sending fails.
    try {
      await sendOTPEmail(email, otp, "signup");
      console.log(`[Signup API] Verification email with OTP sent to ${email}.`);
    } catch (mailError: unknown) { // Use 'unknown' for caught mail errors
      const mailErrorMessage = mailError instanceof Error ? mailError.message : "Unknown email sending error.";
      console.error("[Signup API] Failed to send OTP email:", mailErrorMessage);
      // Optionally: You might log this to a monitoring system or notify an admin.
      // Do NOT return an error to the client here, as the user account was created successfully.
    }

    // Log OTP in development environment for debugging purposes
    if (process.env.NODE_ENV !== "production") {
      console.log(`[Signup API] OTP for ${email}: ${otp}`);
    }

    // Return a success response
    return NextResponse.json(
      {
        message: "Signup successful. A verification code has been sent to your email.",
        email, // Optionally return email for frontend redirection
      },
      { status: 201 } // 201 Created status code
    );
  } catch (error: unknown) { // Use 'unknown' for general caught errors
    // Log the full error for server-side debugging
    const errorMessage = error instanceof Error ? error.message : "An unknown error occurred during signup.";
    console.error("[Signup API] Server error:", errorMessage, error);

    // Handle Zod validation errors specifically if they somehow bypass safeParse (less likely here)
    if (error instanceof ZodError) {
      return NextResponse.json(
        { error: error.errors[0].message },
        { status: 400 }
      );
    }

    // Fallback for any other unexpected errors
    return NextResponse.json(
      { error: "Signup failed due to an internal server error. Please try again." },
      { status: 500 } // 500 Internal Server Error for unexpected issues
    );
  }
}
